### ISSUE TITLE
ModuleNotFoundError: No module named 'scraping_hub'

### ISSUE THREAD

**Issue by sjaanus** [clemfromspace/scrapy-cloudflare-middleware#1]
Is this project active, I see only 1 commit to it?

I am getting this error when adding it to middleware. Any suggestions?

**Comment by Godtooro** [comment]
I’m at the same point at you.
Could anybody help us please?

**Comment by Godtooro** [comment]
Hi!!
Thank you for your support!
The spider is getting closed, take a look:

"C:\Users\Luis\Mister>scrapy crawl mercado -o file.csv -t csv
2018-07-25 21:46:15 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: mercado)

2018-07-25 21:46:15 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9
.7, cssselect 1.0.1, parsel 1.2.0, w3lib 1.18.0, Twisted 17.5.0, Python 2.7.14 |
Anaconda, Inc.| (default, Nov  8 2017, 13:40:45) [MSC v.1500 64 bit (AMD64)], py
OpenSSL 17.5.0 (OpenSSL 1.0.2n  7 Dec 2017), cryptography 2.1.4, Platform Window
s-8-6.2.9200-SP0
2018-07-25 21:46:15 [scrapy.crawler] INFO: Overridden settings: {'NEWSPIDER_MODU
LE': 'mercado.spiders', 'FEED_URI': 'file.csv', 'AUTOTHROTTLE_TARGET_CONCURRENCY
': 2.0, 'SPIDER_MODULES': ['mercado.spiders'], 'AUTOTHROTTLE_START_DELAY': 2, 'B
OT_NAME': 'mercado', 'ROBOTSTXT_OBEY': True, 'USER_AGENT': 'Mozilla/5.0 (X11; Li
nux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0', 'FEED_FORMAT': 'csv', 'AUTOTH
ROTTLE_ENABLED': True, 'DOWNLOAD_DELAY': 2}
2018-07-25 21:46:15 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.throttle.AutoThrottle']
2018-07-25 21:46:16 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'mercado.middlewares.CloudFlareMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-07-25 21:46:16 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-07-25 21:46:16 [scrapy.middleware] INFO: Enabled item pipelines:
['mercado.pipelines.MercadoPipeline']
2018-07-25 21:46:16 [scrapy.core.engine] INFO: Spider opened
2018-07-25 21:46:16 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pag
es/min), scraped 0 items (at 0 items/min)
2018-07-25 21:46:16 [scrapy.extensions.telnet] DEBUG: Telnet console listening o
n 127.0.0.1:6023
2018-07-25 21:46:16 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.m
ister-auto.es/robots.txt> (referer: None)
2018-07-25 21:46:19 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.m
ister-auto.es/global_search2.html?idx=prod_monoindex_ESes&q=FEBI+BILSTEIN> (refe
rer: None)
2018-07-25 21:46:19 [scrapy.core.engine] INFO: Closing spider (finished)
2018-07-25 21:46:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 633,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 20923,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 7, 25, 19, 46, 19, 543000),
 'log_count/DEBUG': 3,
 'log_count/INFO': 7,
 'response_received_count': 2,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 7, 25, 19, 46, 16, 229000)}
2018-07-25 21:46:19 [scrapy.core.engine] INFO: Spider closed (finished)"


My settings.py following your instructions:
"# -*- coding: utf-8 -*-

# Scrapy settings for bitcointalk_bot project
#
# For simplicity, this file contains only settings considered important or
# commonly used. You can find more settings consulting the documentation:
#
#     http://doc.scrapy.org/en/latest/topics/settings.html
#     http://scrapy.readthedocs.org/en/latest/topics/downloader-middleware.html
#     http://scrapy.readthedocs.org/en/latest/topics/spider-middleware.html

BOT_NAME = 'mercado'

SPIDER_MODULES = ['mercado.spiders']
NEWSPIDER_MODULE = 'mercado.spiders'


# Crawl responsibly by identifying yourself (and your website) on the user-agent
USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0'

# Obey robots.txt rules
ROBOTSTXT_OBEY = True

# Configure maximum concurrent requests performed by Scrapy (default: 16)
#CONCURRENT_REQUESTS = 32

# Configure a delay for requests for the same website (default: 0)
# See http://scrapy.readthedocs.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
DOWNLOAD_DELAY = 2

# The download delay setting will honor only one of:
#CONCURRENT_REQUESTS_PER_DOMAIN = 16
#CONCURRENT_REQUESTS_PER_IP = 16

# Disable cookies (enabled by default)
#COOKIES_ENABLED = False

# Disable Telnet Console (enabled by default)
#TELNETCONSOLE_ENABLED = False

# Override the default request headers:
#DEFAULT_REQUEST_HEADERS = {
#   'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
#   'Accept-Language': 'en',
#}

# Enable or disable spider middlewares
# See http://scrapy.readthedocs.org/en/latest/topics/spider-middleware.html
#SPIDER_MIDDLEWARES = {
#    'bitcointalk_bot.middlewares.TutorialSpiderMiddleware': 543,
#}

# Enable or disable downloader middlewares
# See http://scrapy.readthedocs.org/en/latest/topics/downloader-middleware.html
DOWNLOADER_MIDDLEWARES = {
    'mercado.middlewares.CloudFlareMiddleware': 560
}

# Enable or disable extensions
# See http://scrapy.readthedocs.org/en/latest/topics/extensions.html
#EXTENSIONS = {
#    'scrapy.extensions.telnet.TelnetConsole': None,
#}

# Configure item pipelines
# See http://scrapy.readthedocs.org/en/latest/topics/item-pipeline.html
ITEM_PIPELINES = {
    'mercado.pipelines.MercadoPipeline': 100,
}

# Enable and configure the AutoThrottle extension (disabled by default)
# See http://doc.scrapy.org/en/latest/topics/autothrottle.html
AUTOTHROTTLE_ENABLED = True
# The initial download delay
AUTOTHROTTLE_START_DELAY = 2
# The maximum download delay to be set in case of high latencies
#AUTOTHROTTLE_MAX_DELAY = 60
# The average number of requests Scrapy should be sending in parallel to
# each remote server
AUTOTHROTTLE_TARGET_CONCURRENCY = 2.0
# Enable showing throttling stats for every response received:
#AUTOTHROTTLE_DEBUG = False

# Enable and configure HTTP caching (disabled by default)
# See http://scrapy.readthedocs.org/en/latest/topics/downloader-middleware.html#httpcache-middleware-settings
#HTTPCACHE_ENABLED = True
#HTTPCACHE_EXPIRATION_SECS = 0
#HTTPCACHE_DIR = 'httpcache'
#HTTPCACHE_IGNORE_HTTP_CODES = []
#HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'"


And my middleware.py as yours:

# -*- coding: utf-8 -*-

# Define here the models for your spider middleware
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/spider-middleware.html

from scrapy import signals
from cfscrape import get_tokens

import logging

class MercadoSpiderMiddleware(object):
    # Not all methods need to be defined. If a method is not defined,
    # scrapy acts as if the spider middleware does not modify the
    # passed objects.

    @classmethod
    def from_crawler(cls, crawler):
        # This method is used by Scrapy to create your spiders.
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    def process_spider_input(self, response, spider):
        # Called for each response that goes through the spider
        # middleware and into the spider.

        # Should return None or raise an exception.
        return None

    def process_spider_output(self, response, result, spider):
        # Called with the results returned from the Spider, after
        # it has processed the response.

        # Must return an iterable of Request, dict or Item objects.
        for i in result:
            yield i

    def process_spider_exception(self, response, exception, spider):
        # Called when a spider or process_spider_input() method
        # (from other spider middleware) raises an exception.

        # Should return either None or an iterable of Response, dict
        # or Item objects.
        pass

    def process_start_requests(self, start_requests, spider):
        # Called with the start requests of the spider, and works
        # similarly to the process_spider_output() method, except
        # that it doesn’t have a response associated.

        # Must return only requests (not items).
        for r in start_requests:
            yield r

    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)


# Thank you clemfromspace for this middlware
# https://github.com/clemfromspace/scrapy-cloudflare-middleware


class CloudFlareMiddleware:
    """Scrapy middleware to bypass the CloudFlare's anti-bot protection"""

    @staticmethod
    def is_cloudflare_challenge(response):
        """Test if the given response contains the cloudflare's anti-bot protection"""

        return (
            response.status == 200
            and response.headers.get('Server', '').startswith(b'cloudflare')
            and 'jschl_vc' in response.text
            and 'jschl_answer' in response.text
        )

    def process_response(self, request, response, spider):
        """Handle the a Scrapy response"""

        if not self.is_cloudflare_challenge(response):
            return response

        logger = logging.getLogger('cloudflaremiddleware')

        logger.debug(
            'Cloudflare protection detected on %s, trying to bypass...',
            response.url
        )

        cloudflare_tokens, __ = get_tokens(
            request.url,
            user_agent=spider.settings.get('USER_AGENT')
        )

        logger.debug(
            'Successfully bypassed the protection for %s, re-scheduling the request',
            response.url
        )

        request.cookies.update(cloudflare_tokens)
        request.priority = 99999

        return request

Can you help me?

________________________________

**Comment by ihgalis** [comment]
Maybe obeying the robots.txt is the problem. Just have a look at it:

https://www.mister-auto.es/robots.txt

You can change this within the settings: ROBOTSTXT_OBEY = False

And in general: Always try to see the websites without javascript. Just install NoScript or something similiar into your browser and see the page as it is seen by scrapy (not exactly but at least without javascript). Sometimes your crawler doesn't work because contents may be provided with javascript. If you encounter this problem also have a look at the splash middleware: https://github.com/scrapy-plugins/scrapy-splash

Good luck!

**Comment by clemfromspace** [comment]
Hey there, actually the README was wrong, I fixed it, you should put `scrapy_cloudflare_middleware.middlewares.CloudFlareMiddleware` in your `DOWNLOADER_MIDDLEWARES` settings.
